server:
  port: 8080

spring:
  application:
    name: cursor-quitter-web
  
  # 开发环境配置
  profiles:
    active: dev

# 微信配置
wechat:
  app-id: ${WECHAT_APP_ID:your_wechat_app_id}
  app-secret: ${WECHAT_APP_SECRET:your_wechat_app_secret}
  code2-session-url: https://api.weixin.qq.com/sns/jscode2session
  user-info-url: https://api.weixin.qq.com/sns/userinfo

# 日志配置
logging:
  level:
    com.example.cursorquitterweb: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 